const assert = require("assert");
const fs = require("fs");

const lib = fs.readFileSync("apps/rust-api/src/lib.rs", "utf8");
const aiRoutes = fs.readFileSync("apps/rust-api/src/ai_routes.rs", "utf8");
const coachBoundaryProvider = fs.readFileSync("apps/rust-api/src/coach_boundary_provider.rs", "utf8");
const coachBoundaryFeedback = fs.readFileSync("apps/rust-api/src/coach_boundary_feedback.rs", "utf8");
const coachBoundaryFeedbackSummary = fs.readFileSync("apps/rust-api/src/coach_boundary_feedback_summary.rs", "utf8");
const coachBoundaryRoutes = fs.readFileSync("apps/rust-api/src/coach_boundary_routes.rs", "utf8");
const authAccountActions = fs.readFileSync("apps/rust-api/src/auth_account_actions.rs", "utf8");
const authAccountBatchActions = fs.readFileSync("apps/rust-api/src/auth_account_batch_actions.rs", "utf8");
const coachInvitationActionRoutes = fs.readFileSync("apps/rust-api/src/coach_invitation_action_routes.rs", "utf8");
const coachInvitationImportRoutes = fs.readFileSync("apps/rust-api/src/coach_invitation_import_routes.rs", "utf8");
const coachInvitationNotifications = fs.readFileSync("apps/rust-api/src/coach_invitation_notifications.rs", "utf8");
const coachInvitationRoutes = fs.readFileSync("apps/rust-api/src/coach_invitation_routes.rs", "utf8");
const coachInvitations = fs.readFileSync("apps/rust-api/src/coach_invitations.rs", "utf8");
const coachOnboardingEventSummary = fs.readFileSync("apps/rust-api/src/coach_onboarding_event_summary.rs", "utf8");
const coachOnboardingEvents = fs.readFileSync("apps/rust-api/src/coach_onboarding_events.rs", "utf8");
const coachOnboardingReport = fs.readFileSync("apps/rust-api/src/coach_onboarding_report.rs", "utf8");
const coachOnboardingRoutes = fs.readFileSync("apps/rust-api/src/coach_onboarding_routes.rs", "utf8");
const coachOutcomes = [
  "apps/rust-api/src/coach_outcomes.rs",
  "apps/rust-api/src/coach_outcomes/report.rs",
  "apps/rust-api/src/coach_outcomes/metrics.rs",
  "apps/rust-api/src/coach_outcomes/narrative.rs",
  "apps/rust-api/src/coach_outcomes/window.rs"
].map((file) => fs.readFileSync(file, "utf8")).join("\n");
const llmFeedback = fs.readFileSync("apps/rust-api/src/llm_feedback.rs", "utf8");
const llmFeedbackSummary = fs.readFileSync("apps/rust-api/src/llm_feedback_summary.rs", "utf8");
const llmRuns = fs.readFileSync("apps/rust-api/src/llm_runs.rs", "utf8");

assert.match(lib, /mod ai_routes;/);
assert.match(lib, /mod llm_feedback_summary;/);
assert.match(lib, /mod coach_onboarding_event_summary;/);
assert.match(lib, /mod coach_boundary_feedback;/);
assert.match(lib, /mod coach_boundary_feedback_summary;/);
assert.match(lib, /mod coach_onboarding_events;/);
assert.match(lib, /mod coach_onboarding_report;/);
assert.match(lib, /mod coach_onboarding_routes;/);
assert.match(lib, /mod coach_outcomes;/);
assert.match(lib, /mod auth_account_actions;/);
assert.match(lib, /mod auth_account_batch_actions;/);
assert.match(lib, /mod coach_invitation_action_routes;/);
assert.match(lib, /mod coach_invitation_import_routes;/);
assert.match(lib, /mod coach_invitation_notifications;/);
assert.match(lib, /mod coach_invitation_routes;/);
assert.match(lib, /mod coach_invitations;/);
assert.match(lib, /route\("\/api\/score-answer", post\(ai_routes::score_answer\)\)/);
assert.match(lib, /route\("\/api\/generate-kb", post\(ai_routes::generate_kb\)\)/);
assert.match(lib, /route\(\s*"\/api\/coach\/artifacts",\s*post\(ai_routes::generate_coach_artifacts\),\s*\)/s);
assert.match(lib, /route\(\s*"\/api\/coach\/boundary-suggestions",\s*post\(coach_boundary_routes::generate_boundary_suggestions\),\s*\)/s);
assert.match(lib, /route\(\s*"\/api\/coach\/boundary-feedback",\s*get\(coach_boundary_routes::get_boundary_feedback\)\s*\.post\(coach_boundary_routes::record_boundary_feedback\),\s*\)/s);
assert.match(lib, /route\("\/api\/coach\/llm-runs", get\(ai_routes::get_coach_llm_runs\)\)/);
assert.match(lib, /route\(\s*"\/api\/coach\/feedback",\s*get\(ai_routes::get_coach_feedback\)\.post\(ai_routes::record_coach_feedback\),\s*\)/s);
assert.match(lib, /route\(\s*"\/api\/coach\/outcomes",\s*get\(coach_outcomes::get_coach_outcomes\)\.post\(coach_outcomes::record_coach_outcome\),\s*\)/s);
assert.match(lib, /route\(\s*"\/api\/coach\/onboarding-events",\s*get\(coach_onboarding_routes::get_coach_onboarding_events\)\s*\.post\(coach_onboarding_routes::record_coach_onboarding_event\),\s*\)/s);
assert.match(lib, /route\(\s*"\/api\/coach\/onboarding-report",\s*get\(coach_onboarding_routes::get_coach_onboarding_report\),\s*\)/s);
assert.match(lib, /route\(\s*"\/api\/coach\/invitations",\s*get\(coach_invitation_routes::get_coach_invitations\)\s*\.post\(coach_invitation_routes::record_coach_invitation\)\s*\.delete\(coach_invitation_action_routes::delete_coach_invitation_route\),\s*\)/s);
assert.match(lib, /route\("\/api\/transcribe", post\(ai_routes::transcribe\)\)/);

["score_answer", "generate_kb", "generate_coach_artifacts", "get_coach_llm_runs", "record_coach_feedback", "get_coach_feedback", "transcribe"].forEach((handler) => {
  assert.match(aiRoutes, new RegExp(`pub\\(crate\\) async fn ${handler}`));
  assert.doesNotMatch(lib, new RegExp(`async fn ${handler}`));
});
["record_coach_onboarding_event", "get_coach_onboarding_events", "get_coach_onboarding_report"].forEach((handler) => {
  assert.match(coachOnboardingRoutes, new RegExp(`pub\\(crate\\) async fn ${handler}`));
  assert.doesNotMatch(lib, new RegExp(`async fn ${handler}`));
});
["get_coach_outcomes", "record_coach_outcome"].forEach((handler) => {
  assert.match(coachOutcomes, new RegExp(`pub\\(crate\\) async fn ${handler}`));
  assert.doesNotMatch(lib, new RegExp(`async fn ${handler}`));
});
["record_coach_invitation", "get_coach_invitations"].forEach((handler) => {
  assert.match(coachInvitationRoutes, new RegExp(`pub\\(crate\\) async fn ${handler}`));
  assert.doesNotMatch(lib, new RegExp(`async fn ${handler}`));
});
["delete_coach_invitation_route", "update_invitation_batch_status_response", "update_invitation_account_status_response", "update_invitation_account_batch_status_response", "generate_invitation_notifications_response"].forEach((handler) => {
  assert.match(coachInvitationActionRoutes, new RegExp(`pub\\(crate\\) async fn ${handler}`));
  assert.doesNotMatch(lib, new RegExp(`async fn ${handler}`));
});
assert.match(coachInvitationImportRoutes, /pub\(crate\) async fn import_coach_invitations_response/);
assert.doesNotMatch(lib, /async fn import_coach_invitations_response/);

assert.match(aiRoutes, /score_answer_payload/);
assert.match(aiRoutes, /generate_kb_payload/);
assert.match(aiRoutes, /generate_coach_artifacts_payload/);
assert.match(aiRoutes, /coach_llm_run_from_response/);
assert.match(aiRoutes, /insert_llm_run/);
assert.match(aiRoutes, /list_llm_runs/);
assert.match(aiRoutes, /coach_feedback_from_payload/);
assert.match(aiRoutes, /insert_llm_feedback/);
assert.match(aiRoutes, /list_llm_feedback/);
assert.match(aiRoutes, /summarize_llm_feedback/);
assert.match(aiRoutes, /transcribe_upload_response/);
assert.match(aiRoutes, /use crate::ai_transcribe::transcribe_upload_response;/);
assert.match(aiRoutes, /use crate::coach_ai_provider::generate_coach_artifacts_payload;/);
assert.match(aiRoutes, /use crate::llm_feedback::\{\s*coach_feedback_from_payload, insert_llm_feedback, list_llm_feedback,?\s*\};/s);
assert.match(aiRoutes, /use crate::llm_feedback_summary::summarize_llm_feedback;/);
assert.match(aiRoutes, /use crate::llm_runs::\{coach_llm_run_from_response, insert_llm_run, list_llm_runs\};/);
assert.match(aiRoutes, /require_auth/);
assert.match(aiRoutes, /require_permission/);
assert.match(aiRoutes, /parse_json_body/);
assert.match(aiRoutes, /bad_json/);
assert.match(aiRoutes, /json_response/);
assert.match(aiRoutes, /now_millis/);
assert.match(aiRoutes, /ASR_MAX_AUDIO_BYTES/);
assert.match(aiRoutes, /ASR_PROVIDER/);
assert.match(aiRoutes, /ANTHROPIC_BASE_URL/);
assert.match(aiRoutes, /header::CONTENT_TYPE/);
assert.match(coachBoundaryRoutes, /pub\(crate\) async fn generate_boundary_suggestions/);
assert.match(coachBoundaryRoutes, /pub\(crate\) async fn record_boundary_feedback/);
assert.match(coachBoundaryRoutes, /pub\(crate\) async fn get_boundary_feedback/);
assert.match(coachBoundaryRoutes, /generate_boundary_suggestions_payload/);
assert.match(coachBoundaryRoutes, /boundary_feedback_from_payload/);
assert.match(coachBoundaryRoutes, /insert_boundary_feedback/);
assert.match(coachBoundaryRoutes, /list_boundary_feedback/);
assert.match(coachBoundaryRoutes, /summarize_boundary_feedback/);
assert.match(coachBoundaryRoutes, /require_permission\(&auth, "ai:use"\)/);
assert.match(coachBoundaryProvider, /boundary_suggestions_payload/);
assert.match(coachBoundaryProvider, /provider_config_incomplete/);
assert.match(coachOnboardingRoutes, /coach_onboarding_event_from_payload/);
assert.match(coachOnboardingRoutes, /insert_coach_onboarding_event/);
assert.match(coachOnboardingRoutes, /list_coach_onboarding_events/);
assert.match(coachOnboardingRoutes, /summarize_coach_onboarding_events/);
assert.match(coachOnboardingRoutes, /coach_onboarding_report/);
assert.match(coachOnboardingRoutes, /require_permission\(&auth, "ai:use"\)/);
assert.match(coachOnboardingRoutes, /parse_json_body/);
assert.match(coachOnboardingRoutes, /bad_json/);
assert.match(coachOnboardingRoutes, /json_response/);
assert.match(coachOutcomes, /build_coach_outcome_report/);
assert.match(coachOutcomes, /server-weekly-runtime/);
assert.match(coachOutcomes, /coachOutcomeSnapshots/);
assert.match(coachOutcomes, /read_runtime_state/);
assert.match(coachOutcomes, /write_runtime_item/);
assert.match(coachOutcomes, /list_llm_feedback/);
assert.match(coachOutcomes, /summarize_llm_feedback/);
assert.match(coachOutcomes, /require_permission\(&auth, "ai:use"\)/);
assert.match(coachOutcomes, /require_write_permission/);
assert.doesNotMatch(coachOutcomes, /Router/);
assert.match(coachInvitationRoutes, /coach_invitation_from_payload/);
assert.match(coachInvitationRoutes, /upsert_coach_invitation/);
assert.match(coachInvitationRoutes, /list_coach_invitations/);
assert.match(coachInvitationRoutes, /summarize_coach_invitations/);
assert.match(coachInvitationRoutes, /bulk-import/);
assert.match(coachInvitationRoutes, /require_permission\(&auth, "\*"\)/);
assert.match(coachInvitationRoutes, /parse_json_body/);
assert.match(coachInvitationRoutes, /bad_json/);
assert.match(coachInvitationRoutes, /json_response/);
assert.match(coachInvitationActionRoutes, /delete_coach_invitation/);
assert.match(coachInvitationActionRoutes, /update_coach_invitation_batch_status/);
assert.match(coachInvitationActionRoutes, /update_user_account_status/);
assert.match(coachInvitationActionRoutes, /update_user_account_batch_status/);
assert.match(coachInvitationActionRoutes, /invitation_notification_action/);
assert.match(coachInvitationActionRoutes, /require_permission\(&auth, "\*"\)/);
assert.match(coachInvitationActionRoutes, /json_response/);
assert.match(coachInvitationRoutes, /account-batch-status/);
assert.match(coachInvitationRoutes, /notification-draft/);
assert.match(coachInvitationImportRoutes, /import_coach_invitations_response/);
assert.match(coachInvitationImportRoutes, /upsert_coach_invitation/);
assert.match(coachInvitationImportRoutes, /coach_invitation_from_payload/);
assert.doesNotMatch(coachInvitationActionRoutes, /upsert_coach_invitation/);
assert.match(authAccountActions, /pub\(crate\) fn user_accounts_for_management/);
assert.match(authAccountActions, /pub\(crate\) fn update_user_account_status/);
assert.match(authAccountActions, /write_users_config/);
assert.doesNotMatch(authAccountActions, /Router/);
assert.match(authAccountBatchActions, /pub\(crate\) fn update_user_account_batch_status/);
assert.match(authAccountBatchActions, /write_users_config/);
assert.match(authAccountBatchActions, /protected_account/);
assert.doesNotMatch(authAccountBatchActions, /Router/);
assert.match(coachInvitationNotifications, /pub\(crate\) fn invitation_notification_action/);
assert.match(coachInvitationNotifications, /密码请通过单独安全渠道/);
assert.doesNotMatch(coachInvitationNotifications, /upsert_coach_invitation/);
assert.doesNotMatch(coachInvitationNotifications, /write_users_config/);

assert.doesNotMatch(lib, /score_answer_payload/);
assert.doesNotMatch(lib, /generate_kb_payload/);
assert.doesNotMatch(lib, /generate_coach_artifacts_payload/);
assert.doesNotMatch(lib, /coach_feedback_from_payload/);
assert.doesNotMatch(lib, /coach_onboarding_event_from_payload/);
assert.doesNotMatch(lib, /coach_invitation_from_payload/);
assert.doesNotMatch(lib, /build_coach_outcome_report/);
assert.doesNotMatch(lib, /transcribe_upload_response/);
assert.doesNotMatch(lib, /require_permission/);
assert.doesNotMatch(aiRoutes, /read_runtime_state/);
assert.doesNotMatch(aiRoutes, /write_runtime_item/);
assert.doesNotMatch(aiRoutes, /session_cookie/);
assert.doesNotMatch(aiRoutes, /Router/);
assert.doesNotMatch(aiRoutes, /boundary_suggestions_payload/);
assert.doesNotMatch(aiRoutes, /boundary_feedback_from_payload/);
assert.doesNotMatch(aiRoutes, /coach_onboarding_event_from_payload/);
assert.doesNotMatch(aiRoutes, /build_coach_outcome_report/);

assert.match(llmRuns, /pub\(crate\) fn coach_llm_run_from_response/);
assert.match(llmRuns, /pub\(crate\) async fn insert_llm_run/);
assert.match(llmRuns, /pub\(crate\) async fn list_llm_runs/);
assert.match(llmRuns, /INSERT INTO llm_runs/);
assert.match(llmRuns, /FROM llm_runs/);
assert.doesNotMatch(llmRuns, /require_auth/);
assert.doesNotMatch(llmRuns, /Router/);

assert.match(llmFeedback, /pub\(crate\) fn coach_feedback_from_payload/);
assert.match(llmFeedback, /pub\(crate\) async fn insert_llm_feedback/);
assert.match(llmFeedback, /pub\(crate\) async fn list_llm_feedback/);
assert.match(llmFeedback, /INSERT INTO llm_feedback/);
assert.match(llmFeedback, /FROM llm_feedback/);
assert.doesNotMatch(llmFeedback, /require_auth/);
assert.doesNotMatch(llmFeedback, /Router/);
assert.match(llmFeedbackSummary, /pub\(crate\) fn summarize_llm_feedback/);
assert.match(llmFeedbackSummary, /next_prompt_hint/);
assert.doesNotMatch(llmFeedbackSummary, /require_auth/);
assert.doesNotMatch(llmFeedbackSummary, /Router/);
assert.match(coachBoundaryFeedback, /pub\(crate\) fn boundary_feedback_from_payload/);
assert.match(coachBoundaryFeedback, /pub\(crate\) async fn insert_boundary_feedback/);
assert.match(coachBoundaryFeedback, /pub\(crate\) async fn list_boundary_feedback/);
assert.match(coachBoundaryFeedback, /INSERT INTO coach_boundary_feedback/);
assert.match(coachBoundaryFeedback, /FROM coach_boundary_feedback/);
assert.doesNotMatch(coachBoundaryFeedback, /require_auth/);
assert.doesNotMatch(coachBoundaryFeedback, /Router/);
assert.match(coachBoundaryFeedbackSummary, /pub\(crate\) fn summarize_boundary_feedback/);
assert.match(coachBoundaryFeedbackSummary, /next_extraction_hint/);
assert.doesNotMatch(coachBoundaryFeedbackSummary, /require_auth/);
assert.doesNotMatch(coachBoundaryFeedbackSummary, /Router/);
assert.match(coachOnboardingEvents, /pub\(crate\) fn coach_onboarding_event_from_payload/);
assert.match(coachOnboardingEvents, /pub\(crate\) async fn insert_coach_onboarding_event/);
assert.match(coachOnboardingEvents, /pub\(crate\) async fn list_coach_onboarding_events/);
assert.match(coachOnboardingEvents, /INSERT INTO coach_onboarding_events/);
assert.match(coachOnboardingEvents, /FROM coach_onboarding_events/);
assert.doesNotMatch(coachOnboardingEvents, /require_auth/);
assert.doesNotMatch(coachOnboardingEvents, /Router/);
assert.match(coachOnboardingEventSummary, /pub\(crate\) fn summarize_coach_onboarding_events/);
assert.match(coachOnboardingEventSummary, /highest_risk_label/);
assert.doesNotMatch(coachOnboardingEventSummary, /require_auth/);
assert.doesNotMatch(coachOnboardingEventSummary, /Router/);
assert.match(coachOnboardingReport, /pub\(crate\) async fn coach_onboarding_report/);
assert.match(coachOnboardingReport, /summarize_batches/);
assert.match(coachOnboardingReport, /top_drop_offs/);
assert.doesNotMatch(coachOnboardingReport, /require_auth/);
assert.doesNotMatch(coachOnboardingReport, /Router/);
assert.match(coachInvitations, /pub\(crate\) fn coach_invitation_from_payload/);
assert.match(coachInvitations, /pub\(crate\) async fn upsert_coach_invitation/);
assert.match(coachInvitations, /pub\(crate\) async fn update_coach_invitation_batch_status/);
assert.match(coachInvitations, /pub\(crate\) async fn delete_coach_invitation/);
assert.match(coachInvitations, /pub\(crate\) async fn list_coach_invitations/);
assert.match(coachInvitations, /pub\(crate\) fn summarize_coach_invitations/);
assert.match(coachInvitations, /INSERT INTO coach_invitations/);
assert.match(coachInvitations, /template_version/);
assert.match(coachInvitations, /DELETE FROM coach_invitations/);
assert.match(coachInvitations, /FROM coach_invitations/);
assert.match(coachInvitations, /invalid_invitation_status/);
assert.doesNotMatch(coachInvitations, /require_auth/);
assert.doesNotMatch(coachInvitations, /Router/);

console.log("rust ai routes boundary tests passed");
