const assert = require("assert");
const fs = require("fs");

const lib = fs.readFileSync("apps/rust-api/src/lib.rs", "utf8");
const aiRoutes = fs.readFileSync("apps/rust-api/src/ai_routes.rs", "utf8");
const aiTranscribe = fs.readFileSync("apps/rust-api/src/ai_transcribe.rs", "utf8");
const aiTools = fs.readFileSync("apps/rust-api/src/ai_tools.rs", "utf8");
const coachAiProvider = fs.readFileSync("apps/rust-api/src/coach_ai_provider.rs", "utf8");
const coachAiTools = fs.readFileSync("apps/rust-api/src/coach_ai_tools.rs", "utf8");
const coachBoundaryProvider = fs.readFileSync("apps/rust-api/src/coach_boundary_provider.rs", "utf8");
const coachBoundaryRoutes = fs.readFileSync("apps/rust-api/src/coach_boundary_routes.rs", "utf8");
const coachBoundarySuggestions = fs.readFileSync("apps/rust-api/src/coach_boundary_suggestions.rs", "utf8");
const coachOpportunitySignals = fs.readFileSync("apps/rust-api/src/coach_opportunity_signals.rs", "utf8");
const coachOpportunitySignalParse = fs.readFileSync("apps/rust-api/src/coach_opportunity_signal_parse.rs", "utf8");
const coachJdInsights = fs.readFileSync("apps/rust-api/src/coach_jd_insights.rs", "utf8");
const coachRolePlaybook = fs.readFileSync("apps/rust-api/src/coach_role_playbook.rs", "utf8");
const coachAiToolsTests = fs.readFileSync("apps/rust-api/src/coach_ai_tools_tests.rs", "utf8");

assert.match(lib, /mod ai_tools;/);
assert.match(lib, /mod ai_transcribe;/);
assert.match(lib, /mod ai_routes;/);
assert.match(lib, /mod coach_ai_tools;/);
assert.match(lib, /mod coach_ai_provider;/);
assert.match(lib, /mod coach_ai_provider_format;/);
assert.match(lib, /mod coach_role_playbook;/);
assert.match(lib, /mod coach_opportunity_signals;/);
assert.match(lib, /mod coach_opportunity_signal_parse;/);
assert.match(lib, /mod coach_jd_insights;/);
assert.match(lib, /mod coach_boundary_provider;/);
assert.match(lib, /mod coach_boundary_routes;/);
assert.match(lib, /mod coach_boundary_suggestions;/);
assert.match(lib, /mod coach_ai_tools_tests;/);
assert.match(aiRoutes, /use crate::ai_tools::\{generate_kb_payload, score_answer_payload\};/);
assert.match(aiRoutes, /use crate::ai_transcribe::transcribe_upload_response;/);
assert.match(aiRoutes, /use crate::coach_ai_provider::generate_coach_artifacts_payload;/);
assert.match(aiTools, /pub\(crate\) fn score_answer_payload/);
assert.match(aiTools, /pub\(crate\) fn generate_kb_payload/);
assert.match(coachAiTools, /pub\(crate\) fn coach_artifacts_payload/);
assert.match(coachRolePlaybook, /pub\(crate\) fn role_family_playbook/);
assert.match(coachRolePlaybook, /question_bank_for/);
assert.match(coachRolePlaybook, /questionBank/);
assert.match(coachRolePlaybook, /测试策略、质量风险、自动化覆盖/);
assert.match(coachOpportunitySignals, /pub\(crate\) fn coach_opportunity_context/);
assert.match(coachOpportunitySignalParse, /pub\(crate\) fn normalize_signals/);
assert.match(coachOpportunitySignalParse, /pub\(crate\) fn build_focus_label/);
assert.match(coachOpportunitySignalParse, /机会：/);
assert.match(coachJdInsights, /pub\(crate\) fn build_jd_insights/);
assert.match(coachJdInsights, /准备故障恢复案例/);
assert.match(coachOpportunitySignals, /JD解析：/);
assert.match(coachBoundaryRoutes, /pub\(crate\) async fn generate_boundary_suggestions/);
assert.match(coachBoundaryRoutes, /require_permission\(&auth, "ai:use"\)/);
assert.match(coachBoundaryRoutes, /generate_boundary_suggestions_payload/);
assert.match(coachBoundaryProvider, /pub\(crate\) async fn generate_boundary_suggestions_payload/);
assert.match(coachBoundaryProvider, /anthropic-compatible/);
assert.match(coachBoundaryProvider, /ai_generation_fallback/);
assert.match(coachBoundarySuggestions, /pub\(crate\) fn boundary_suggestions_payload/);
assert.match(coachBoundarySuggestions, /coach-boundary-suggestions-v1/);
assert.match(coachAiProvider, /pub\(crate\) async fn generate_coach_artifacts_payload/);
assert.match(aiTranscribe, /pub\(crate\) fn transcribe_upload_response/);
assert.match(aiTranscribe, /fn multipart_audio_len/);
assert.match(aiTools, /score_answer_payload_requires_question_and_answer/);
assert.match(aiTools, /generate_kb_payload_marks_provider_fallback_warning/);
assert.match(coachAiToolsTests, /coach_artifacts_requires_profile/);
assert.match(coachAiToolsTests, /coach_artifacts_uses_boundary_and_marks_fallback/);
assert.match(coachAiToolsTests, /coach_artifacts_uses_role_family_when_target_role_is_empty/);
assert.match(coachAiToolsTests, /boundary_suggestions_extract_common_topics_for_any_role/);
assert.match(aiTranscribe, /transcribe_upload_response_validates_upload_and_provider/);

assert.doesNotMatch(lib, /fn multipart_audio_len/);
assert.doesNotMatch(lib, /"provider": "local-fallback"/);
assert.doesNotMatch(lib, /"audio_too_large"/);
assert.doesNotMatch(lib, /"provider_not_implemented"/);
assert.match(aiRoutes, /score_answer_payload/);
assert.match(aiRoutes, /generate_kb_payload/);
assert.match(aiRoutes, /transcribe_upload_response/);
assert.doesNotMatch(aiTools, /transcribe_upload_response/);
assert.doesNotMatch(aiTools, /multipart_audio_len/);
assert.doesNotMatch(aiTools, /audio_too_large/);
assert.doesNotMatch(aiTools, /provider_not_implemented/);
assert.doesNotMatch(aiTranscribe, /score_answer_payload/);
assert.doesNotMatch(aiTranscribe, /generate_kb_payload/);
assert.doesNotMatch(aiTranscribe, /local-fallback/);
assert.doesNotMatch(aiTools, /require_auth/);
assert.doesNotMatch(aiTools, /require_permission/);
assert.doesNotMatch(aiTools, /AuthState/);
assert.doesNotMatch(aiTools, /Sqlite/);
assert.doesNotMatch(aiTools, /AppState/);
assert.doesNotMatch(coachAiTools, /require_auth/);
assert.doesNotMatch(coachAiTools, /require_permission/);
assert.doesNotMatch(coachAiTools, /AuthState/);
assert.doesNotMatch(coachAiTools, /Sqlite/);
assert.doesNotMatch(coachAiTools, /AppState/);
assert.doesNotMatch(coachAiProvider, /require_auth/);
assert.doesNotMatch(coachAiProvider, /require_permission/);
assert.doesNotMatch(coachAiProvider, /AppState/);
assert.doesNotMatch(coachBoundarySuggestions, /require_auth/);
assert.doesNotMatch(coachBoundarySuggestions, /require_permission/);
assert.doesNotMatch(coachBoundarySuggestions, /AppState/);
assert.doesNotMatch(coachBoundarySuggestions, /Router/);
assert.doesNotMatch(coachBoundaryProvider, /require_auth/);
assert.doesNotMatch(coachBoundaryProvider, /require_permission/);
assert.doesNotMatch(coachBoundaryProvider, /AppState/);
assert.doesNotMatch(aiTranscribe, /require_auth/);
assert.doesNotMatch(aiTranscribe, /require_permission/);
assert.doesNotMatch(aiTranscribe, /AuthState/);
assert.doesNotMatch(aiTranscribe, /Sqlite/);
assert.doesNotMatch(aiTranscribe, /AppState/);

console.log("rust ai tools boundary tests passed");
