const assert = require("assert");
const fs = require("fs");

const lib = fs.readFileSync("apps/rust-api/src/lib.rs", "utf8");
const bootstrap = fs.readFileSync("apps/rust-api/src/app_bootstrap.rs", "utf8");
const authConfig = fs.readFileSync("apps/rust-api/src/auth_config.rs", "utf8");
const authHash = fs.readFileSync("apps/rust-api/src/auth_hash.rs", "utf8");
const authTokens = fs.readFileSync("apps/rust-api/src/auth_tokens.rs", "utf8");
const authUsers = fs.readFileSync("apps/rust-api/src/auth_users.rs", "utf8");
const authValues = fs.readFileSync("apps/rust-api/src/auth_values.rs", "utf8");
const authBearer = fs.readFileSync("apps/rust-api/src/auth_bearer.rs", "utf8");
const authRoutes = fs.readFileSync("apps/rust-api/src/auth_routes.rs", "utf8");
const authState = fs.readFileSync("apps/rust-api/src/auth_state.rs", "utf8");
const healthRoutes = fs.readFileSync("apps/rust-api/src/health_routes.rs", "utf8");

assert.match(lib, /mod auth_bearer;/);
assert.match(lib, /mod auth_config;/);
assert.match(lib, /mod auth_hash;/);
assert.match(lib, /mod auth_tokens;/);
assert.match(lib, /mod auth_users;/);
assert.match(lib, /mod auth_values;/);
assert.match(healthRoutes, /use crate::auth_config::get_auth_config;/);
assert.match(bootstrap, /use crate::auth_config::\{UserConfig, get_auth_config\};/);
assert.match(bootstrap, /async fn sync_configured_users\(db: &SqlitePool, users: &\[UserConfig\]\)/);
assert.match(authRoutes, /use crate::auth_config::get_auth_config;/);
assert.match(authRoutes, /use crate::auth_hash::\{constant_time_eq, sha256_hex\};/);
assert.match(authState, /use crate::auth_config::\{AuthConfig, UserConfig, get_auth_config\};/);
assert.match(authBearer, /use crate::auth_hash::\{constant_time_eq, sha256_hex\};/);
assert.match(authUsers, /pub\(crate\) struct UserConfig/);
assert.match(authTokens, /pub\(crate\) struct BearerToken/);
assert.match(authConfig, /pub\(crate\) struct AuthConfig/);
assert.match(authConfig, /pub\(crate\) use crate::auth_tokens::BearerToken;/);
assert.match(authConfig, /use crate::auth_tokens::bearer_tokens_from_env;/);
assert.match(authConfig, /pub\(crate\) use crate::auth_users::UserConfig;/);
assert.match(authConfig, /pub\(crate\) fn get_auth_config/);
assert.match(authHash, /pub\(crate\) fn sha256_hex/);
assert.match(authHash, /pub\(crate\) fn is_hex64/);
assert.match(authConfig, /use crate::auth_hash::\{is_hex64, sha256_hex\};/);
assert.match(authConfig, /use crate::auth_users::/);
assert.match(authConfig, /fn load_configured_users/);
assert.match(authTokens, /pub\(crate\) fn bearer_tokens_from_env/);
assert.match(authTokens, /fn bearer_tokens_from_value/);
assert.match(authTokens, /bearer_tokens_from_value_filters_invalid_and_unknown_users/);
assert.match(authUsers, /users_from_config_object_normalizes_defaults_and_hashes_passwords/);
assert.match(authUsers, /pub\(crate\) fn users_from_config_object/);
assert.match(authUsers, /pub\(crate\) fn users_by_name/);
assert.match(authUsers, /pub\(crate\) fn primary_data_scope/);
assert.match(authValues, /pub\(crate\) fn string_field/);
assert.match(authValues, /pub\(crate\) fn string_array_field/);

assert.doesNotMatch(lib, /struct UserConfig/);
assert.doesNotMatch(lib, /struct BearerToken/);
assert.doesNotMatch(lib, /struct AuthConfig/);
assert.doesNotMatch(lib, /fn get_auth_config/);
assert.doesNotMatch(lib, /use auth_config::get_auth_config;/);
assert.doesNotMatch(lib, /fn load_configured_users/);
assert.doesNotMatch(lib, /fn users_from_config_object/);
assert.doesNotMatch(lib, /fn bearer_tokens_from_env/);
assert.doesNotMatch(lib, /MIN_SESSION_SECRET_LENGTH/);
assert.doesNotMatch(authConfig, /struct BearerToken/);
assert.doesNotMatch(authConfig, /fn bearer_tokens_from_env/);
assert.doesNotMatch(authConfig, /fn bearer_tokens_from_value/);
assert.doesNotMatch(authConfig, /JOB_SPRINT_BEARER_TOKENS_JSON/);
assert.doesNotMatch(authConfig, /JOB_SPRINT_BEARER_TOKENS_FILE/);
assert.doesNotMatch(authConfig, /HashSet/);
assert.doesNotMatch(authConfig, /axum::/);
assert.doesNotMatch(authConfig, /Sqlite/);
assert.doesNotMatch(authConfig, /Response/);
assert.doesNotMatch(authConfig, /use sha2::/);
assert.doesNotMatch(authConfig, /fn is_hex64/);
assert.doesNotMatch(authConfig, /struct UserConfig/);
assert.doesNotMatch(authConfig, /fn users_from_config_object/);
assert.doesNotMatch(authConfig, /fn users_by_name/);
assert.doesNotMatch(authConfig, /fn primary_data_scope/);
assert.doesNotMatch(authConfig, /fn string_array_field/);
assert.doesNotMatch(authConfig, /fn string_field/);
assert.doesNotMatch(authTokens, /struct AuthConfig/);
assert.doesNotMatch(authTokens, /session_secret/);
assert.doesNotMatch(authState, /sha256_hex/);
assert.doesNotMatch(authUsers, /std::env/);
assert.doesNotMatch(authUsers, /std::fs/);
assert.doesNotMatch(authValues, /UserConfig/);

console.log("rust auth config boundary tests passed");
